sonar_driver:
        ros__parameters:
                port: "/dev/sonar_driver"
                topic: "/sonar"
                rate: "10"
                baudrate: 115200
gamepad_driver:
        ros__parameters:
                topic: "/cmd_vel"
                rate: 20
                gain_lin: 1.0
                gain_ang: 0.33

motor_driver:
       ros__parameters:
               topic: "/cmd_vel"
               port: "/dev/motor_driver" 

motor_diag:
        ros__parameters:
                topic: "/motor_diag"
                port: "/dev/motor_diag"
                rate: "5"
joy_driver:
        ros__parameters:
                topic_vel: "/cmd_vel"
                topic_btn: "/btn"
                port: "/dev/joydriver"
                rate: "30"
                gain_lin: 1.0
                gain_ang: 8.0
gps_driver:
        ros__parameters:
                port: "/dev/ublox"
                topic: "/fix"
                baudrate: 9600 
