version: "3.3"
services:
    scoomatic-base:
        image: scoomatic-base
        devices: 
            - "/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0:/dev/rplidar"
            - "/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0:/dev/motor_controller"
        network_mode: "host"
        command: "./start.sh"
#    scoomatic-nav:
#        image: scoomatic-nav
#        command: "./start.sh"
