sonar_driver:
        ros__parameters:
                port: "/dev/ttyUSB0"
                topic: "/sonar"
gamepad_driver:
        ros__parameters:
                topic: "/cmd_vel"
                rate: 5

motor_driver:
       ros__parameters:
               topic: "/cmd_vel"
               port: "/dev/ttyUSB0" 
